### ISSUE TITLE
[Tip] oh-my-zsh auto-completion glitches

### ISSUE THREAD

**Issue by glubsy** [illinoisjackson/even-better-ls#24]
When using oh-my-zsh auto-completion by pressing TAB key, the suggested file list is glitching when the cursor moves around the list (not exactly sure why).

Simply disable the colors in ls to fix it. In your ~/.zshrc: 
`DISABLE_LS_COLORS="true"`

And it will fix the problem.

**Comment by stuaxo** [comment]
Hm, there must be a way to make this work only for autocomplete and not everywhere.

**Comment by mattbauch** [comment]
I think the glitch is not hard to explain.   
Originally the colors for `ls` are supposed to be control sequences only. The ls command basically adds a color prefix and a color suffix (to reset the color) to each filename. In pseudo-code it looks like `{red}filename.txt{reset color}`. And the stuff in curly braces is not printed. 
With our little hack we add two printable characters, a glyph and an empty space after the control sequences. Now our color is 2 printable characters long instead of 0. So the string after replacement looks like this `{red}@ filename.txt{reset}` (@ being the glyph that will become an icon with the right font). 

That's also the reason why we have to patch `ls` to prevent weird line-break issues. 

Autocompletion uses color codes as well. But to highlight the currently selected item it uses its own color code (bright background on my theme), since there cannot be two colorcodes on one string, it overwrites ours. And suddenly the color string is again 0 printable characters long. So when an item is highlighted it shifts to the left. When you unselect it it gets shifted back to its original position. 

    {red}filename.txt{clear}     // highlighted
    {red}@ filename.txt{clear}   // not highlighted

To fix the problem we have to add 2 additional characters to the color of the highlighted string. Ideally the characters would be the icon of the selected file and a space. One can also use an arrow to indicate selection or just two spaces. While it's certainly possible to do I'm not sure where to look. 

----

So for now I just came up with a way to disable the icons in the highlighter but keep the colors. Here's how

1. create another version of the ls_colors_icons_generator.py
2. change the color format creation in line 847 so it no longer outputs the glyph and the space. 

Change from 

    return "m%s\x1b" % ("%s%s " % (color_seq(f,b,other),get_unicode(c)))

to 

    return "m%s\x1b" % ("%s" % (color_seq(f,b,other)))

3. export the output of the changed version to a different environment variable named `LS_COLORS_ONLY`
4. add a `zstyle` that uses the `LS_COLORS_ONLY` colors. 

the tail of my .zshrc:

    # alias for the patched ls 
    alias ls="/Users/matthias/.bin/iconls/ls --color=auto"
    # original output of the generator. I changed its name to match its output
    export LS_COLORS="$(python /Users/matthias/.bin/iconls/ls_colors_icons_generator.py)"
    # my patched generator, outputs only color codes
    export LS_COLORS_ONLY="$(python /Users/matthias/.bin/iconls/ls_colors_generator.py)"
    # I found that zstyle definition somewhere on the internet. 
    # then changed LS_COLORS to LS_COLORS_ONLY to only get colored output
    zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS_ONLY}

Result: 
![screen shot 2018-11-18 at 04 45 24](https://user-images.githubusercontent.com/437012/48668576-0fecdf80-eaf1-11e8-966d-e3c57aedd216.png)
